- name: Build servers
  hosts: localhost
  tasks:
    - name: Provision instances
      local_action:
          module: rax
          name: "{{ item.name }}"
          flavor: "{{ item.flavor }}"
          image: "{{ item.image }}"
          group: "{{ item.group }}"
          meta: "{{ item.meta }}"
          key_name: "{{ item.key_name }}"
          wait: no
          auto_increment: False
      register: rax
      with_items: "{{ rax_servers }}"
