- name: Set VXLAN interface 
  hosts: all
  vars:
    vxlan_inteface_name: vxlan100
    vxlan_interface_id: 100
    vxlan_interface_dstport: 4789
    vxlan_interface_mtu: 1450
  tasks: 
  - debug: var=item
    with_items: "{{ groups['controller'] | difference([inventory_hostname]) }}"
  
  - name: Create VXLAN device
    shell: |
       ip link add "{{vxlan_inteface_name}}" type vxlan id "{{vxlan_interface_id}}" dstport "{{vxlan_interface_dstport}}" local "{{hostvars[inventory_hostname]['ansible_eth1']['ipv4']['address']}}" 
       ip link set dev "{{vxlan_inteface_name}}" mtu "{{vxlan_interface_mtu}}"

  - name: Add neighbours to VXLAN
    shell: |
       bridge fdb append 00:00:00:00:00:00 dev "{{vxlan_inteface_name}}" dst "{{hostvars[item]['ansible_eth1']['ipv4']['address']}}"
    with_items: "{{ groups['controller'] | difference([inventory_hostname]) }}"

  - name: Online intefaces
    shell: |
       ip link set  dev "{{vxlan_inteface_name}}" up 
