- name: SSH keys
  hosts: all
  tasks:
    - name: Set authorized key for user ubuntu copying it from current user
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
